In [1]:
import  torch
x = torch.ones(2,2,requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [2]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [3]:
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
z = y*y*3
out = z.mean()
print(z,out)
#因为这里添加了mean求均值的函数，所以需要使用z.mean()

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [5]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
#a*3为矩阵中的每一个对应值都乘3
#a-1为矩阵中的每一个对应值都减去1
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [6]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


这里计算对应的矩阵为由4.5构成的相应矩阵，计算过程为
$o=\frac{1}{4}\sum_{i}z_{i}$,$z_{i}=3(x_i+2)^2$,$z_i|_{x_i=1}=27$
(前面乘$\frac{1}{4}$，因为总共有四个数值，矩阵为2乘2的矩阵)
因此，$\frac{\partial o}{\partial x_i}={\frac{3}{2}}(x_i+2)$，因此$\frac{\partial o}{\partial x_i}|_{x_i=1}={\frac{9}{2}}=4.5$

https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#sphx-glr-beginner-blitz-autograd-tutorial-py
接下来这个教程网站上面的内容本质上写的就是连续梯度下降为分别梯度下降的对应导数相乘的结果

In [10]:
x = torch.randn(3,requires_grad = True)
print('x = ***')
print(x)
y = x*2
print('y = ***')
print(y)
result = y.data.norm()
print('result = ***')
print(result)
while  y.data.norm() < 1000:
#.data.norm()函数为对应的L2范数，平方加和后开根号
    y = y*2
#vector-Jacobian 乘积使得它非常方便地将一个额外的梯度编外
#一个模型，并且模型有非线性的输出
print('y = ###')
print(y)


x = ***
tensor([-1.1621, -0.6468,  0.9048], requires_grad=True)
y = ***
tensor([-2.3242, -1.2936,  1.8097], grad_fn=<MulBackward0>)
result = ***
tensor(3.2172)
y = ###
tensor([-1189.9915,  -662.3100,   926.5590], grad_fn=<MulBackward0>)


In [9]:
v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
#大概2次方了十次，所以公式整体为y=1024x，然后求导完之后为[1024,1024,1024],
#最后每次再乘相应的向量[0.1,1.0,0.0001]
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [11]:
print(x.requires_grad)
print((x**2).requires_grad)

with  torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [12]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())
#x与y两者的内容一样，但是y中的requires_grad的值
#为False

True
False
tensor(True)
