In [3]:
from  __future__  import  print_function
import  torch
print("torch version {}".format(torch.__version__))
print("cuda is available {}".format(torch.cuda.is_available()))

torch version 1.3.1
cuda is available True


In [4]:
x = torch.empty(5,3)
print(x)

tensor([[2.5124e-18, 1.9421e+31, 2.7491e+20],
        [6.1949e-04, 7.1856e+22, 4.3605e+27],
        [2.3329e-18, 1.9284e+31, 3.2314e-18],
        [2.6991e-06, 1.6806e-04, 5.4425e+22],
        [3.3274e+21, 8.4944e+20, 5.4126e+22]])


In [5]:
x = torch.rand(5,3)
print(x)

tensor([[0.3235, 0.4991, 0.7837],
        [0.8626, 0.2673, 0.3167],
        [0.6688, 0.1018, 0.4429],
        [0.2786, 0.9495, 0.2139],
        [0.5311, 0.5326, 0.8354]])


In [6]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.6091,  0.2242,  0.3536],
        [ 0.9503, -1.6211, -0.3935],
        [ 0.4379, -0.8636, -1.2143],
        [ 0.3725, -0.4807,  0.4987],
        [ 1.8902,  0.1961,  0.4996]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5,3)
print('x = ***')
print(x)
print('y = ***')
print(y)
print('x+y = ***')
print(x+y)
print(torch.add(x,y))

x = ***
tensor([[ 2.6091,  0.2242,  0.3536],
        [ 0.9503, -1.6211, -0.3935],
        [ 0.4379, -0.8636, -1.2143],
        [ 0.3725, -0.4807,  0.4987],
        [ 1.8902,  0.1961,  0.4996]])
y = ***
tensor([[0.7092, 0.7137, 0.0829],
        [0.7914, 0.5126, 0.1084],
        [0.0584, 0.6283, 0.3802],
        [0.0878, 0.8101, 0.6152],
        [0.9300, 0.4623, 0.1249]])
x+y = ***
tensor([[ 3.3183,  0.9379,  0.4365],
        [ 1.7417, -1.1085, -0.2851],
        [ 0.4962, -0.2354, -0.8341],
        [ 0.4602,  0.3294,  1.1139],
        [ 2.8201,  0.6584,  0.6244]])
tensor([[ 3.3183,  0.9379,  0.4365],
        [ 1.7417, -1.1085, -0.2851],
        [ 0.4962, -0.2354, -0.8341],
        [ 0.4602,  0.3294,  1.1139],
        [ 2.8201,  0.6584,  0.6244]])


In [12]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)
#torch.add(x,y,out=result)中为将x与y两个数组相加
#out输出的结果为result

tensor([[ 3.3183,  0.9379,  0.4365],
        [ 1.7417, -1.1085, -0.2851],
        [ 0.4962, -0.2354, -0.8341],
        [ 0.4602,  0.3294,  1.1139],
        [ 2.8201,  0.6584,  0.6244]])


In [13]:
y.add_(x)
print(y)

tensor([[ 3.3183,  0.9379,  0.4365],
        [ 1.7417, -1.1085, -0.2851],
        [ 0.4962, -0.2354, -0.8341],
        [ 0.4602,  0.3294,  1.1139],
        [ 2.8201,  0.6584,  0.6244]])


In [16]:
print('x = ***')
print(x)
print('x[:,1] = ***')
print(x[:,1])

x = ***
tensor([[ 2.6091,  0.2242,  0.3536],
        [ 0.9503, -1.6211, -0.3935],
        [ 0.4379, -0.8636, -1.2143],
        [ 0.3725, -0.4807,  0.4987],
        [ 1.8902,  0.1961,  0.4996]])
x[:,1] = ***
tensor([ 0.2242, -1.6211, -0.8636, -0.4807,  0.1961])


In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [19]:
import  numpy  as  np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [21]:
#if  CUDA  is  available
#We will use "torch.device" to move tensors in and out of GPU
if  torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))

tensor([[ 3.6091,  1.2242,  1.3536],
        [ 1.9503, -0.6211,  0.6065],
        [ 1.4379,  0.1364, -0.2143],
        [ 1.3725,  0.5193,  1.4987],
        [ 2.8902,  1.1961,  1.4996]], device='cuda:0')
tensor([[ 3.6091,  1.2242,  1.3536],
        [ 1.9503, -0.6211,  0.6065],
        [ 1.4379,  0.1364, -0.2143],
        [ 1.3725,  0.5193,  1.4987],
        [ 2.8902,  1.1961,  1.4996]], dtype=torch.float64)
